add missed parameter for topology dualtor-aa-56 on th2 (#20484)
What is the motivation for this PR?
encountered keyerror issue for topology topology dualtor-aa-56 on th2. as below:

qos/test_qos_sai.py::TestQosSai::testParameter[single_asic]
-------------------------------- live log setup --------------------------------
02/09/2025 10:56:46 __init__._fixture_generator_decorator    L0088 ERROR  |
KeyError('wm_pg_shared_lossless')
Traceback (most recent call last):
  File "/var/src/sonic-mgmt_testbed-bjw3-can-dual-t0-7260-2/tests/common/plugins/log_section_start/__init__.py", line 84, in _fixture_generator_decorator
    res = next(it)
  File "/var/src/sonic-mgmt_testbed-bjw3-can-dual-t0-7260-2/tests/qos/qos_sai_base.py", line 1767, in dutQosConfig
    qosParams = qpm.run()
  File "/var/src/sonic-mgmt_testbed-bjw3-can-dual-t0-7260-2/tests/qos/files/brcm/qos_param_generator.py", line 521, in run
    self.prepare_default_parameters()
  File "/var/src/sonic-mgmt_testbed-bjw3-can-dual-t0-7260-2/tests/qos/files/brcm/qos_param_generator.py", line 636, in prepare_default_parameters
    self.create_default_pg_shared_watermark_parameter(pg_profile)
  File "/var/src/sonic-mgmt_testbed-bjw3-can-dual-t0-7260-2/tests/qos/files/brcm/qos_param_generator.py", line 575, in create_default_pg_shared_watermark_parameter
    self.qos_params[self.speed_cable_len][pg_profile] = self.qos_params[pg_profile]
KeyError: 'wm_pg_shared_lossless'
How did you do it?
add missing qos parameter which value come from topo-any.

How did you verify/test it?
local test

Signed-off-by: Raghavendran Ramanathan <rraghav@cisco.com>